SSpro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chat.urls')),
    path('account/',include('SSapp.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
   
    path('checkview', views.checkview, name='checkview'),
    path('', views.home, name='home'),
    path('<str:room>/', views.room, name='room'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

SSapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from SSapp.models import Blog_Post, Mentorinfo,User,Usrinfo
from SSapp.models import Comment
from django.forms import ModelForm
########from .models import Comment##########################################################################################################



class CommentForm(forms.ModelForm):
    commenter = forms.CharField(max_length=20, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder':'username'
    }))
    body = forms.CharField(max_length=100, widget = forms.Textarea(attrs={
        'class': 'form-control', 'placeholder': 'Comment here', 'rows': 3
    }))
    class Meta:
        model = Comment
        fields = ['commenter', 'body']






class BlogForm(forms.ModelForm): 
    class Meta:
        model = Blog_Post
        fields = ['id','image','title','body','slug'] 

        
        



class MentorReg(UserCreationForm):
    email = forms.EmailField(required=True)
    password = forms.PasswordInput()

    class Meta(UserCreationForm):
        model = User
        fields = ['id','email','username']
      
    
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email = self.cleaned_data.get('email')
        user.is_mentor = True
        user.save()
        crt = Mentorinfo.objects.create(user=user)
        return user


class UsrReg(UserCreationForm):
    email = forms.EmailField(required=True)
    password = forms.PasswordInput()

    class Meta(UserCreationForm):
        model  = User
        fields = ['id','email','username']
        widgets = {
           
            'email': forms.EmailInput(attrs={'class': 'input-box', 'placeholder': 'Email address:'}),
            'password1': forms.PasswordInput(attrs={'class': 'input-box', 'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'class': 'input-box', 'placeholder': 'Password Again'}),
        }
       
        

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email = self.cleaned_data.get('email')
        user.is_user = True
        user.save()
        usr = Usrinfo.objects.create(user=user)
        return user        



class MentorinfoForm(forms.ModelForm):
    full_Name=forms.CharField(label='Full Name',widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = Mentorinfo
        fields = ['full_Name', 'address','phone','country' ,'states','email','git_hub','insta_link','linked_in','city','field_of_interest','total_earnings_by','company_name','experience_yrs','description_in_short','future_goals']
        widgets={
            'full_Name':forms.TextInput(attrs={'class':'form-control'}),
            'phone':forms.TextInput(attrs={'class':'form-control'}),
            'full_Name':forms.TextInput(attrs={'class':'form-control'}),
            'city':forms.TextInput(attrs={'class':'form-control'}),
            'field_of_interest':forms.TextInput(attrs={'class':'form-control'}),
            'git_hub':forms.TextInput(attrs={'class':'form-control'}),
            'insta_link':forms.TextInput(attrs={'class':'form-control'}),
            'linked_in':forms.TextInput(attrs={'class':'form-control'}),
            'total_earnings_by':forms.TextInput(attrs={'class':'form-control'}),
            'company_name':forms.TextInput(attrs={'class':'form-control'}),
            'experience_yrs':forms.TextInput(attrs={'class':'form-control'}),
            'description_in_short':forms.TextInput(attrs={'class':'form-control'}),
            'future_goals':forms.TextInput(attrs={'class':'form-control'}),
            'address':forms.TextInput(attrs={'class':'form-control'}),
            'country':forms.TextInput(attrs={'class':'form-control'}),
            'states':forms.TextInput(attrs={'class':'form-control'}),
        }





##################################################################################################################

templates/frontend_blog.html
{% extends 'frontend_base.html' %}
{% load static %}

{% block css %}

  /*Google Font*/
@import url("https://fonts.googleapis.com/css?family=Acme|Lobster|Patua+One|Rubik|Sniglet");


*{
    box-sizing: border-box;
}

header,
section{
    overflow-x:hidden ;
}

:root {
    --Sniglet-font: "Sniglet", cursive;
    --Rubik: "Rubik", cursive;
    --Patua: "Patua One", cursive;
    --Lobster: "lobster", cursive;
    --light-black: #2e2c2caf;
    --bggradient: linear-gradient(to bottom, #b524dd, #fd62c2);
    --light-gray: rgba(255, 255, 255, 0.877);
  }

  header a {
    font-family: var(--Sniglet-font);
    font-size: 0.9em;
    color: whitesmoke;
  }

  header{
    background: #dd2476;
    background: var(--bggradient);
  }
  
  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 2px 15px 0px rgba(0, 0, 0, 0.2);
    z-index: 1;
  }

  .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }
  
  .dropdown-content a:hover {
    background-color: #ddd;
  }
  
  .dropdown:hover .dropdown-content {
    display: block;
  }

  header .nav-item:last-child {
    padding-right: 10.5em;
  }
  
  header .nav-item {
    padding: 0.9em;
  }

  header .navbar-brand {
    padding-left: 8rem;
  }
  
  header .nav-link:hover {
    color: black;
  }
  
  header .row .col-md-7 {
    padding: 22vmin 1vmin;
    padding-bottom: 35vmin;
  }
  
  header .row .col-md-5 {
    padding: 4.2vmin 1vmin;
  }
  
  header .row .col-md-5 img {
    width: 90%;
  }
  
  header {
    background: #ff512f;
    /* fallback for old browsers */
    background: var(--bggradient);
  }
  
  header .container .col-md-7 {
    /* font-family: "Rubik", sans-serif; */
    font-family: "Lobster",sans-serif;
  }
  
  header .container .col-md-7 h6 {
    padding: 1vmin;
    letter-spacing: 4px;
  }
  
  header .container .col-md-7 h1 {
    font-size: 8.5vmin;
    font-weight: bold;
    padding: 0.1em 0em;
  }
  
  header .container .col-md-7 p {
    padding: 1vmin 5vmin;
  }
  
  .primary-btn {
    border-radius: 30px;
    font-weight: bold;
  }


  


    
  footer {
    background: rgba(0, 0, 0, 0.815);
    overflow-x: hidden;
    padding: 14vmin 18vmin;
  }
  
  footer p > span {
    color: #ff512f;
  }
  
  footer input {
    border: none !important;
  }
  
  footer input::placeholder {
    color: white !important;
  }
  
  footer .input-group .input-group-text {
    background: var(--bggradient);
    border: none;
  }
  
  footer .column i {
    color: #dd2476;
  }
  
  /* It is Adjacent sibling combinator */
  
  footer .column i + i {
    padding: 0 0.5em;
  }
  
  .sticky {
    position: fixed;
    top: 0;
    width: 100%;
    background: rgba(0, 0, 0, 0.815);
    z-index: 9999;
    transition: all 1.5s ease;
  }







.container{
    width: 100%;
    height: 100vh;
    font-family: sans-serif;
    background: rgb(237, 215, 234);
    color: #fff;
    display: flex;
    align-items: center;
    justify-content: center;
}

.card{
    width: 350px;
    height: 500px;
    box-shadow: 0 0 40px 20px rgba(0, 0, 0, 0.26);
    perspective: 1000px;
    border-radius: 50px;
}

.inner-box{
    position:relative;
    width: 100%;
    height:100%;
   
    transition: transform 1s;
    transform-style: preserve-3d;
}

.card-front, .card-back{
    position: absolute;
    width: 100%;
    height: 100%;
    background-position: center;
    background-size: cover;
    background-image: linear-gradient(rgba(47, 7, 30, 0.8),rgba(47,7,30,0.8)),url(back.png);
    padding: 55px;
    box-sizing: border-box;
    backface-visibility: hidden;
    border-radius: 15px;
}

.card-back{
    transform: rotateY(180deg);
}

.card h2{
    font-weight: normal;
    font-size: 24px;
    text-align: center;
    margin-bottom: 20px;
}

.input-box{
    width: 100%;
    background: transparent;
    border: 1px solid #fff;
    margin:6px 0;
    height: 32px;
    border-radius: 20px;
    padding: 0 10px;
    box-sizing: border-box;
    outline: none;
    text-align:center ;
    color: white;
}

::placeholder{
    color: #fff;
    font-size: 12px;
}

button{
    width: 100%;
    background: transparent;
    border: 1px solid #fff;
    margin: 35px 0 10px;
    height: 32px;
    font-size: 12px;
    border-radius: 20px;
    padding: 0 10px;
    box-sizing: border-box;
    outline: none;
    color: #fff;
    cursor: pointer;
}

.submit-btn{
    position: relative;
}

.submit-btn::after{
    content: '\27a4';
    color: #333;
    line-height: 32px;
    font-size: 17px;
    height: 32px;
    width: 32px;
    border-radius: 50%;
    background:#fff;
    position: absolute;
    right: -1px;
    top: -1px;
}

span{
    font-size: 13px;
    margin-left: 10px;

}

.card .btn{
    margin-top: 50px;
}

/* .card .a{
    color: #fff;
    text-decoration: none;
    display: block;
    text-align: center;
    font-size: 13px;
    margin-top: 8px;
} */





{% endblock css %}



{% block nav %}

<header>
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg">
          <a class="navbar-brand" href="{% url 'frontend_home' %}"><i class="fa-solid fa-crown fa-2x mx-3"></i> SheBuilds</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">

              <i class="fas fa-align-right text-light"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="mr-auto"> </div>
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'sginpg_user' %}">Mentor info <span class="sr-only">(current)</span></a>
                </li>
                {% if not request.user.is_authenticated %}
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'sg_user' %}">User signup</a>
                </li>
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'sg_mentor' %}">Mentor signup</a>
                </li> 
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'sgin_user' %}">User login</a>
                </li>
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'sgin_mentor' %}">Mentor login</a>
                </li>  
          
                {% endif %}

                {% if  request.user.is_authenticated %}
               
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'home' %}">Chats room</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'contact_us' %}">Contact</a>
                </li>
          
                {% endif %}

                 {% comment %} <li class="nav-item">
                  <a class="nav-link" href="#scholarships">Scholarship</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#womenrights">Women Rights</a>
                </li>


                <li class="nav-item">
                  <a class="nav-link" href="#mentorships">Mentorship</a>
                </li>
           {% endcomment %}
          


                 

                <!-- <li class="nav-item dropdown">
                  <div class="dropdown">
                    <a href="#" class="nav-link">Pages</a>
                    <div class="dropdown-content">
                         <a href="#">About</a>
                         <a href="#">Help </a>
                    </div>
                  </div>
                </li> -->

                  {% if request.user.is_mentor %}
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'sginpg_mentor' %}">Update profile</a>
                </li>
                  {% endif %}


                    

                {% if request.user.is_user %}
              
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'addPost' %}">Add Post</a>
                </li>
                 

                 
                

                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'my_posts' %}">My posts</a>
                </li>

                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'index' %}">Feeds</a>
                </li>

                 {% endif %}

                  <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout_user' %}" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <b> <i class="fas fa-user-alt"></i>   {{ request.user }}</b>
                  </a>
                 </li>

              </ul>
            </div>
          </nav>
    </div>

</header>


{% endblock nav %}



{% block body  %}



{% for message in messages %}
<div class="alert alert-info alert-dismissible fade show" style="position:absolute;z-index:20;width:100%;" role="alert">
  <strong> {{ message }} </strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}

  <div class="container">



    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{post.title}}</h1>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">{{post.writer}}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on {{post.created_on}}</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="{{post.image.url}}" alt="">

        <hr>

        <!-- Post Content -->
        <p>{{post.body}}</p>

        
          
        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">

            <form method="POST">
                {% csrf_token %}
               {{form.commenter}} <br>
              {{form.body}}<br>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>

          </div>
        </div>

        <!-- Single Comment -->
        
        {% for comment in comments %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.commenter}}</h5>
            {{comment.body}}
          </div>
        </div>
        {% endfor %}
      </div>



{% endblock body %}

templates/frontend_blog_detail.html
{% extends 'frontend_base.html' %}
{% load static %}


{% block nav %}

<header>
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand" href="{% url 'frontend_home' %}"><i class="fa-solid fa-crown fa-2x mx-3"></i> SheBuilds</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">

              <i class="fas fa-align-right text-light"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="mr-auto"> </div>
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'sginpg_user' %}">Mentor info <span class="sr-only">(current)</span></a>
                </li>
                {% if not request.user.is_authenticated %}
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'sg_user' %}">User signup</a>
                </li>
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'sg_mentor' %}">Mentor signup</a>
                </li> 
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'sgin_user' %}">User login</a>
                </li>
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'sgin_mentor' %}">Mentor login</a>
                </li>  
          
                {% endif %}

                {% if  request.user.is_authenticated %}
               
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'home' %}">Chats room</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'contact_us' %}">Contact</a>
                </li>
          
                {% endif %}

                 {% comment %} <li class="nav-item">
                  <a class="nav-link" href="#scholarships">Scholarship</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#womenrights">Women Rights</a>
                </li>


                <li class="nav-item">
                  <a class="nav-link" href="#mentorships">Mentorship</a>
                </li>
           {% endcomment %}
          


                 

                <!-- <li class="nav-item dropdown">
                  <div class="dropdown">
                    <a href="#" class="nav-link">Pages</a>
                    <div class="dropdown-content">
                         <a href="#">About</a>
                         <a href="#">Help </a>
                    </div>
                  </div>
                </li> -->

                  {% if request.user.is_mentor %}
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'sginpg_mentor' %}">Update profile</a>
                </li>
                  {% endif %}


                    

                {% if request.user.is_user %}
              
                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'addPost' %}">Add Post</a>
                </li>
                 

                 
                

                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'my_posts' %}">My posts</a>
                </li>

                 <li class="nav-item">
                  <a class="nav-link" href="{% url 'index' %}">Feeds</a>
                </li>

                 {% endif %}

                  <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout_user' %}" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <b> <i class="fas fa-user-alt"></i>   {{ request.user }}</b>
                  </a>
                 </li>

              </ul>
            </div>
          </nav>
    </div>

</header>


{% endblock nav %}


{% block body %}



{% for message in messages %}
<div class="alert alert-info alert-dismissible fade show" style="position:absolute;z-index:20;width:100%;" role="alert">
  <strong> {{ message }} </strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}

  <div class="container">



    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h4 class="mt-4">{{post.title}}</h4>

        <!-- Author -->
        <p class="lead">
          by
          <a href="#">{{post.writer}}</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Posted on {{post.created_on}}</p>

        <hr>

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="{{post.image.url}}" alt="">

        <hr>

          {% comment %} <p class="card-text"><a href="{% url 'send_request_user' post.writer %}" class="btn btn-danger">Request for details</a></p> {% endcomment %}

        <!-- Post Content -->
        <p>{{post.body}}</p>

        
          
        <hr>
        

        <!-- Comments Form -->
        <div class="card my-4">
          <h6 class="card-header">Leave a Comment:</h6>
          <div class="card-body">

                <form method="POST">
                {% csrf_token %}
                <input type="hidden" value="{{request.user}}" name="commenter" class="form-control" placeholder="username" maxlength="20" required id="id_commenter"> 
                 <hr>
                <textarea name="body" cols="40" rows="3" class="form-control" maxlength="100" required id="id_body">
               </textarea><br>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>

          </div>
        </div>

        <!-- Single Comment -->
        
        {% for comment in comments %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.commenter}}</h5>
            {{comment.body}}
          </div>
        </div>
        {% endfor %}
      </div>

   
{% endblock body %}

templates/frontend_house.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0 auto;
  max-width: 800px;
  padding: 0 20px;
}

.container {
  border: 2px solid #dedede;
  background-color: #f1f1f1;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}

.darker {
  border-color: #ccc;
  background-color: #ddd;
}

.container::after {
  content: "";
  clear: both;
  display: table;
}

.container img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
}

.container img.right {
  float: right;
  margin-left: 20px;
  margin-right:0;
}

.time-right {
  float: right;
  color: #aaa;
}

.time-left {
  float: left;
  color: #999;
}
</style>
</head>
<body>


<div align="center">
    <h2>Django Chat</h2>
</div>


<div class="container">
    <style>
    input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    }

    input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }

    input[type=submit]:hover {
    background-color: #45a049;
    }

    div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
    }
    </style>

    <form id="post-form" method="POST" action="{% url 'checkview' %}">
        {% csrf_token %}
        <label>Room Name</label>
        <input type="text" name="room_name" id="room_name" width="100px" />
        <label>Username</label>
        <input type="text" name="username" id="username" width="100px" />
        <input type="submit" value="Enter Room">
    </form>
</div>


</body>


</html>

templates/frontend_room.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0 auto;
  max-width: 800px;
  padding: 0 20px;
}

.container {
  border: 2px solid #dedede;
  background-color: #f1f1f1;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}

.darker {
  border-color: #ccc;
  background-color: #ddd;
}

.container::after {
  content: "";
  clear: both;
  display: table;
}

.container img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
}

.container img.right {
  float: right;
  margin-left: 20px;
  margin-right:0;
}

.time-right {
  float: right;
  color: #aaa;
}

.time-left {
  float: left;
  color: #999;
}
</style>
<script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
</head>
<body>

<h2>{{room}} - DjChat</h2>

<div id="display">

<!-- <div class="container darker">
  <b>Tom</b><p>Hello Everyone, How Are You Guys Doing?</p>
  <span class="time-left">20th, April 2021</span>
</div> -->

</div>

<script>
$(document).ready(function(){

setInterval(function(){
    $.ajax({
        type: 'GET',
        url : "/getMessages/{{room}}/",
        success: function(response){
            console.log(response);
            $("#display").empty();
            for (var key in response.messages)
            {
                var temp="<div class='container darker'><b>"+response.messages[key].user+"</b><p>"+response.messages[key].value+"</p><span class='time-left'>"+response.messages[key].date+"</span></div>";
                $("#display").append(temp);
            }
        },
        error: function(response){
            alert('An error occured')
        }
    });
},1000);
})
</script>


<div class="container">
    <style>
    input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    }

    input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }

    input[type=submit]:hover {
    background-color: #45a049;
    }

    div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
    }
    </style>

    <form id="post-form">
        {% csrf_token %}
        <input type="hidden" name="username" id="username" value="{{username}}"/>
        <input type="hidden" name="room_id" id="room_id" value="{{room_details.id}}"/>
        <input type="text" name="message" id="message" width="100px" />
        <input type="submit" value="Send">
    </form>
</div>


</body>

<script type="text/javascript">
  $(document).on('submit','#post-form',function(e){
    e.preventDefault();

    $.ajax({
      type:'POST',
      url:'/send',
      data:{
          username:$('#username').val(),
          room_id:$('#room_id').val(),
          message:$('#message').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(data){
         //alert(data)
      }
    });
    document.getElementById('message').value = ''
  });
</script>

</html>